export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCEEDED = 'FETCH_TASKS_SUCCEEDED';
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED';

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCEEDED = 'CREATE_TASK_SUCCEEDED';
export const CREATE_TASK_FAILED = 'CREATE_TASK_FAILED';

export const DELETE_TASKS = 'DELETE_TASKS';
export const DELETE_TASKS_START = 'DELETE_TASKS_START';
export const DELETE_TASKS_SUCCEEDED = 'DELETE_TASKS_SUCCEEDED';
export const DELETE_TASKS_FAILED = 'DELETE_TASKS_FAILED';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_START = 'UPDATE_TASK_START';
export const UPDATE_TASK_SUCCEEDED = 'UPDATE_TASK_SUCCEEDED';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';

export const BULK_UPDATE_TASKS = 'BULK_UPDATE_TASKS';
export const BULK_UPDATE_TASKS_START = 'BULK_UPDATE_TASKS_START';
export const BULK_UPDATE_TASKS_SUCCEEDED = 'BULK_UPDATE_TASKS_SUCCEEDED';
export const BULK_UPDATE_TASKS_FAILED = 'BULK_UPDATE_TASKS_FAILED';

export const INIT_TASKS = 'INIT_TASKS';
export const SET_TASK = 'SET_TASK';
export const SET_TASKS = 'SET_TASKS';
export const REMOVE_TASKS = 'REMOVE_TASKS';