export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCEEDED = 'FETCH_TASKS_SUCCEEDED';
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED';

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCEEDED = 'CREATE_TASK_SUCCEEDED';
export const CREATE_TASK_FAILED = 'CREATE_TASK_FAILED';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCEEDED = 'DELETE_TASK_SUCCEEDED';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_START = 'UPDATE_TASK_START';
export const UPDATE_TASK_SUCCEEDED = 'UPDATE_TASK_SUCCEEDED';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';

export const INIT_TASKS = 'INIT_TASKS';
export const SET_TASK = 'SET_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';