export const INIT_TASKS = 'INIT_TASKS';
export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCEEDED = 'FETCH_TASKS_SUCCEEDED';
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED';

export const SET_TASKS = 'SET_TASKS';

export const SAVE_TASKS = 'SAVE_TASKS';
export const SAVE_TASKS_START = 'SAVE_TASKS_START';
export const SAVE_TASKS_SUCCEEDED = 'SAVE_TASKS_SUCCEEDED';
export const SAVE_TASKS_FAILED = 'SAVE_TASKS_FAILED';